routes/web.php
<?php

use App\Models\Participant;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoothController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\ClassroomController;
use App\Http\Controllers\MainStageController;
use App\Http\Controllers\NotifikasiController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\PreferencesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentHistoryController;
use App\Http\Controllers\PaymentConfirmationController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\PollingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware('auth')->group(function() {
    Route::get('/' , [HomeController::class , 'index'])->name('index');

    Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function () {
        Route::group(['prefix' => 'preferences' , 'as' => 'preferences.'], function () {
            Route::get('/' , [PreferencesController::class , 'index'])->name('index');
            Route::get('/event' , [PreferencesController::class , 'event'])->name('event');
            Route::post('/event/update/{preferences}' , [PreferencesController::class , 'eventUpdate'])->name('event-update');
            Route::get('/zoom' , [PreferencesController::class , 'zoom'])->name('zoom');
            Route::post('/zoom/update/{preferences}' , [PreferencesController::class , 'zoomUpdate'])->name('zoom-update');

            Route::get('/landing-page' , [PreferencesController::class , 'landing'])->name('landing');
            Route::post('/landing/update/{preferences}' , [PreferencesController::class , 'landingUpdate'])->name('landing-update');

            Route::get('/login' , [PreferencesController::class , 'login'])->name('login');
            Route::post('/login/update/{preferences}' , [PreferencesController::class , 'loginUpdate'])->name('login-update');

            Route::get('/payment' , [PreferencesController::class , 'payment'])->name('payment');
            Route::post('/payment/update/{preferences}' , [PreferencesController::class , 'paymentUpdate'])->name('payment-update');

            Route::get('/web' , [PreferencesController::class , 'web'])->name('web');
            Route::post('/web/update/{preferences}' , [PreferencesController::class , 'webUpdate'])->name('web-update');

            Route::post('/speaker/create' , [PreferencesController::class , 'speakerInsert'])->name('speaker.create');
            Route::get('/speaker/delete/{speaker}' , [PreferencesController::class , 'speakerDelete'])->name('speaker.delete');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');
            
        });

        Route::group(['prefix' => 'participant' , 'as' => 'participant.'], function (){
            Route::get('/web-regisration', [ParticipantController::class , 'web'])->name('web-regis');
            Route::get('/invitation', [ParticipantController::class , 'invite'])->name('invite');
            Route::get('/create' ,[ParticipantController::class , 'create'])->name('create');
            Route::post('/store' ,[ParticipantController::class , 'store'])->name('store');
            Route::get('/detail/{participant}', [ParticipantController::class , 'show'])->name('show');
            Route::get('/{participant}' ,[ParticipantController::class , 'destroy'])->name('delete');
            Route::get('/update/{participant}' ,[ParticipantController::class , 'edit'])->name('edit');
            Route::post('/edit/{participant}' ,[ParticipantController::class , 'update'])->name('update');
            
        });
        
        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'notifications' , 'as' => 'notif.'], function () {
            Route::get('/', [NotifikasiController::class , 'index'])->name('index');
            Route::get('/create' ,[NotifikasiController::class , 'create'])->name('create');
            Route::post('/store' ,[NotifikasiController::class , 'store'])->name('store');
            Route::get('/{notif}' ,[NotifikasiController::class , 'delete'])->name('delete');
            Route::get('/update/{notif}' ,[NotifikasiController::class , 'edit'])->name('edit');
            Route::post('/edit/{notif}' ,[NotifikasiController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');

        });

        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
            Route::get('/schedule/{ticket}' ,[TicketController::class , 'schedule'])->name('schedule');
            Route::get('/schedule-delete/{ticket}' ,[TicketController::class , 'scheduleDelete'])->name('schedule.delete');
        });

        Route::group(['prefix' => 'schedule' , 'as' => 'schedule.'], function () {
            /* Main Stage */
            Route::group(['prefix' => 'main-stage' , 'as' => 'main_stage.'], function () {
                Route::get('/', [MainStageController::class , 'index'])->name('index');
                Route::get('/create', [MainStageController::class , 'create'])->name('create');
                Route::post('/store', [MainStageController::class , 'store'])->name('store');
                Route::get('/{main_stage}/edit', [MainStageController::class , 'edit'])->name('edit');
                Route::post('/{main_stage}/update', [MainStageController::class , 'update'])->name('update');
                Route::get('/{main_stage}', [MainStageController::class , 'delete'])->name('delete');
                Route::get('/{main_stage}/attachment', [MainStageController::class , 'attachment'])->name('attachment');
                Route::get('/{main_stage}/attachment/create', [MainStageController::class , 'attachmentCreate'])->name('attachment.create');

app/Models/Banner.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Banner extends Model
{
    use HasFactory;

    protected $table = 'banners';
    protected $guarded = [];
}

app/Http/Controllers/BannerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Banner;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\File;
use Yajra\DataTables\Facades\DataTables;

class BannerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function image()
    {
        if(request()->ajax()){
            $data = Banner::where('status',1)->orderBy('order','ASC')->get();
            return DataTables::of($data)->make(true);
        }

        return view('pages.banner.image');
    }

    public function youtube()
    {
        if(request()->ajax()){
            $data = Banner::where('status',2)->orderBy('order','ASC')->get();
            return DataTables::of($data)->make(true);
        }

        return view('pages.banner.youtube');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $data = null;
        $order = null;

        return view('pages.banner.action',compact('data','order'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        if($request->status == 1){
            request()->validate([
                'status' => 'required',
                'image' => 'required|max:4000',
            ]);
        }else{
            request()->validate([
                'status' => 'required',
                'url' => 'required|url',
            ]);
        }

        if($file = $request->file('image')){
            $name_file = $file->hashName();
            $destinasi = 'img/banner/';
            $file->move($destinasi, $name_file);
        }else{
            $name_file = null;
        }

        $banner = Banner::where('status',$request->status)->latest('order')->first();
        if($banner !== null){
            $no = $banner->order;
        }else{
            $no = 0;
        }

        $data = [
            'image' => $name_file,
            'url' => $request->url,
            'status' => $request->status,
            'order' => $no + 1,
        ];
        

        $status = Banner::create($data)->status;

        if($status == 1){
            return redirect()->route('admin.banner.image');
        }else{
            return redirect()->route('admin.banner.youtube');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Banner $banner)
    {
        $data = $banner;
        $order = Banner::where('status',$banner->status);
        return view('pages.banner.action',compact('data','order'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Banner $banner)
    {

        if($file = $request->file('image')){
            $name_file = $file->hashName();
            $destinasi = 'img/banner/';
            $file->move($destinasi, $name_file);
        }else{
            $name_file = $banner->image;
        }

        $data = [
            'image' => $name_file,
            'url' => $request->url,
            'status' => $request->status,
            'order' => $request->order,
        ];
        
        Banner::where('status',$banner->status)->where('order',$request->order)->update(['order' => $banner->order]);

        $banner->update($data);

        if($banner->status == 1){
            return redirect()->route('admin.banner.image');
        }else{
            return redirect()->route('admin.banner.youtube');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Banner $banner)
    {
        $no = $banner->order;

        $sortUp = Banner::where('status',$banner->status)->where('order',$no+1)->update(['order' => $banner->order]);

        File::delete(public_path('img/banner/',$banner->image));
        $banner->delete();

        return response()->json();
    }
}

resources/views/pages/banner/action.blade.php
@extends('layouts.app')
@section('content')

<link rel="stylesheet" href="/app-assets/css/uploader.css">

<div class="content-header row">
	<div class="content-header-left col-md-9 col-12 mb-2">
		<div class="row breadcrumbs-top">
			<div class="col-12">
				<div class="breadcrumb-wrapper">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="#">Home</a>
						</li>
						<li class="breadcrumb-item"><a href="#">Banner</a>
						</li>
						<li class="breadcrumb-item active">
                            @if ($data !== null)
                                Update Banner
                            @else
                                Create Banner
                            @endif
						</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="content-body">
	<!-- Validation -->
	<section class="bs-validation">
        @if ($data !== null)
		    <form action="{{ route('admin.banner.update',$data->id) }}" method="POST" enctype='multipart/form-data'>        
        @else
		    <form action="{{ route('admin.banner.store') }}" id="jquery-val-form" method="POST" enctype='multipart/form-data'>
        @endif
            @csrf
			<div class="row">
				<!-- Bootstrap Validation -->
				<div class="col-md-12 col-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Banner</h4>
						</div>
						<div class="card-body">
                            <div class="form-group">
                                <label class="form-label" for="Status">Status</label>
                                <select class="form-control status @error('status') border-danger @enderror" name="status">
                                    @if ($data !== null)
                                        <option value="{{ $data->status }}">{{ $data->status == 1 ? 'Image' : 'Youtube'}}</option>
                                    @else
                                        <option value="0">Choise Type Banner</option>
                                        <option value="1">Image</option>
                                        <option value="2">Youtube</option>
                                    @endif
                                </select>
                                @error('status')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>

                            <div class="file-upload @error('image') border-danger @enderror" id="content-image" style="display: none;">
                                <button class="file-upload-btn" type="button" onclick="$('.file-upload-input').trigger( 'click' )">Add image</button>
                                <div class="image-upload-wrap">
                                    <input class="file-upload-input" type='file' onchange="readURL(this);" accept="image/*" name="image" />
                                    <div class="drag-text">
                                        @if ($data !== null)
                                            <img class="file-upload-image" src="/img/banner/{{ $data ? $data->image : '' }}" alt="your image" />
                                        @else
                                            <h3>Drag and drop a file or select add Image</h3>
                                        @endif
                                    </div>
                                </div>
                                <div class="file-upload-content">
                                    <img class="file-upload-image" src="/img/banner/{{ $data ? $data->image : '' }}" alt="your image" />
                                    <div class="image-title-wrap">
                                        <button type="button" onclick="removeUpload()" class="remove-image">Remove <span class="image-title">Uploaded Image</span></button>
                                    </div>
                                </div>
                                @error('image')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>
                            
                            <div class="form-group" id="url-youtube" style="display: none;">
								<label class="form-label" for="name">Url</label>
                                <input type="text" id="url" class="form-control @error('url') border-danger @enderror" placeholder="Input banner url ..." value="{{ $data ? $data->url : '' }}" name="url" />
                                @error('url')
                                    <span class="text-danger">{{ $message }}</span>
                                @enderror
                            </div>

                            @if ($order !== null)
                                <div class="form-group">
                                    <label class="form-label" for="name">Sort</label>
                                    <select name="order" class="form-control">
                                        <option value="{{ $data->order }}">{{ $data->order }}</option>
                                        @foreach ($order as $item)
                                            <option value="{{ $item->order }}">{{ $item->order }}</option>
                                        @endforeach
                                    </select>
                                </div>
                            @endif
						</div>
					</div>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col-md-6">
					<button type="submit" class="btn btn-primary">Save Changes</button>
				</div>
			</div>
		</form>
	</section>
</div>
<script src="/app-assets/vendors/js/vendors.min.js"></script>
<script src="/app-assets/vendors/js/extensions/dropzone.min.js" defer></script>
<script src="/app-assets/js/scripts/forms/form-file-uploader.js" defer></script>

@if ($data !== null)
    @if ($data->status == '1')
        <script>
                $("#content-image").css({"display": "inline"});
                $('#url-youtube').hide();
        </script>
    @else
        <script>
            $("#content-image").hide();
            $('#url-youtube').css({"display": "inline"});
        </script>
    @endif
@endif

<script>
    function readURL(input) {
        if (input.files && input.files[0]) {

            var reader = new FileReader();

            reader.onload = function(e) {
            $('.image-upload-wrap').hide();

            $('.file-upload-image').attr('src', e.target.result);
            $('.file-upload-content').show();

            $('.image-title').html(input.files[0].name);
            };

            reader.readAsDataURL(input.files[0]);

        } else {
            removeUpload();
        }
    }

    function removeUpload() {
        $('.file-upload-input').replaceWith($('.file-upload-input').clone());
        $('.file-upload-content').hide();
        $('.image-upload-wrap').show();
    }

    $(function (){

        $('.image-upload-wrap').bind('dragover', function () {
            $('.image-upload-wrap').addClass('image-dropping');
        });

        $('.image-upload-wrap').bind('dragleave', function () {
                $('.image-upload-wrap').removeClass('image-dropping');
        });

        $("select.status").change(function(){
            var selected = $(this).children("option:selected").val();
            if(selected == 1){
                $("#content-image").css({"display": "inline"});
                $('#url-youtube').hide();
            }else if(selected == 2){
                $("#content-image").hide();
                $('#url-youtube').css({"display": "inline"});
            }
        });
    });
</script>

@endsection

resources/views/pages/banner/image.blade.php
@extends('layouts.app')
@section('content')

<div class="content-overlay"></div>
    <div class="header-navbar-shadow"></div>
    <div class="content-wrapper">
        <div class="content-header row">
            <div class="content-header-left col-md-9 col-12 mb-2">
                <div class="row breadcrumbs-top">
                    <div class="col-12">
                        <h2 class="content-header-title float-left mb-0">Banner</h2>
                        <div class="breadcrumb-wrapper">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="index.html">Home</a>
                                </li>
                                <li class="breadcrumb-item"><a href="#">Banner Image</a>
                                </li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="content-body">
            <!-- Basic table -->
            <section id="ajax-datatable">
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header border-bottom">
                                <h4 class="card-title">Banner Image</h4>
                                <a href="{{ route('admin.banner.create') }}" class="btn btn-primary">Add Data</a>
                            </div>
                            <div class="card-datatable">
                                <table class="table" id="data-banner">
                                    <thead>
                                        <tr>
                                            <th>No</th>
                                            <th>No</th>
                                            <th>Image</th>
                                            <th>Type</th>
                                            <th>Sort</th>
                                            <th>Action</th>
                                        </tr>
                                    </thead>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </section>
            <!--/ Basic table -->


        </div>
    </div>

    <!-- BEGIN: Vendor JS-->
    <script src="/app-assets/vendors/js/vendors.min.js"></script>
    <script src="/app-assets/js/scripts/ui/ui-feather.js" defer></script>
    <!-- BEGIN Vendor JS-->

    <!-- BEGIN: Page Vendor JS-->
    <script src="/app-assets/js/scripts/components/components-dropdowns.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js" defer></script>
    <script src="/app-assets/vendors/js/tables/datatable/responsive.bootstrap4.js" defer></script>

    <script src="/app-assets/js/scripts/tables/table-datatables-advanced.js" defer></script>
    <!-- END: Page Vendor JS-->
    <!-- BEGIN: Page JS-->
    @if (session('created'))
        <script>
            $(function(){
                toastr['success']('👋 Yes Data Created !!.', 'Created Success', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });
            });
        </script>
    @elseif(session('updated'))
        <script>
            $(function(){
                toastr['success']('👋 Yes Data Updated !!.', 'Updated Success', {
                    closeButton: true,
                    tapToDismiss: false,
                    progressBar: true,
                });
            });
        </script>
    @endif

    <script>
        $(function(){
            $.ajaxSetup({
                headers: {
                    'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
                }
            });

            var table = $('#data-banner').DataTable({
                processing: true,
                serverSide: true,
                ajax: "{{ route('admin.banner.image') }}",
                columns: [
                    {
                        data: null, "sortable": false,
                        render: function (data, type, row, meta) { return meta.row + meta.settings._iDisplayStart + 1; },
                    },
                    {
                        data: null, "sortable": false,
                        render: function (data, type, row, meta) { return meta.row + meta.settings._iDisplayStart + 1; },
                    },
                    {
                        data: 'image',
                        render: (image) => /* html */`
                            <img src="/img/banner/${image}" class="w-50">
                        `
                    },
                    {
                        data: 'status',
                        "render" : function(data, type, row){
                            if(row.status == 1){
                                return '<span class="btn text-success">Image</span>';
                            }
                        }
                    },
                    {
                        data: 'order',
                        name: 'order',
                    },
                    {
                        data: 'id',
                        render: (id) => /* html */`
                            <a href="/admin/banner/update/${id}" class="btn text-warning dropdown-item"></i>Update</a>
                            <a class="dropdown-item btn text-danger" onclick="hapus(${id})"></i>Delete</a>
                        `
                    },
                ],
                columnDefs: [
                    {
                    className: 'control',
                    orderable: false,
                    targets: 0
                    }
                ],
                dom:
                    '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
                orderCellsTop: true,
                responsive: {
                    details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function (row) {
                        var data = row.data();
                        return 'Details of ' + data['full_name'];
                        }
                    }),
                    type: 'column',
                    renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                        tableClass: 'table'
                    })
                    }
                },
                language: {
                    paginate: {
                    // remove previous & next text from pagination
                    previous: '&nbsp;',
                    next: '&nbsp;'
                    }
                },
                drawCallback: () => {
                    $('.delete').click(function () {
                    const id = $(this).data(id)
                    })
                }
            });
            
        });

        function hapus(id){
            clearToastObj = toastr['error'](
                'Are You Delete?<br /><br /><button type="button" class="btn btn-danger btn-sm delete">Yes</button>',
                'Deleted',
                {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                tapToDismiss: false,
                }
            );

            if (clearToastObj.find('.delete').length) {
                clearToastObj.delegate('.delete', 'click', function () {
                    toastr.clear(clearToastObj, { force: true });
                    clearToastObj = undefined;
                    $.ajax({
                        method: "GET",
                        url: "/admin/banner" + '/' + id,
                        success: function (data) {
                            toastr['success']('👋 Yes Data Deleted !!.', 'Progress Bar', {
                                closeButton: true,
                                tapToDismiss: false,
                                progressBar: true,
                            });
                            location.reload();
                        },
                        error: function (data) {
                            toastr['success']('👋 Chocolate oat cake jelly oat cake candy jelly beans pastry.', 'Progress Bar', {
                                closeButton: true,
                                tapToDismiss: false,
                                progressBar: true,
                                rtl: isRtl
                            });
                        }
                    });
                });
            }
        }
    </script>
@endsection