routes/web.php
<?php

use App\Models\Participant;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoothController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\ClassroomController;
use App\Http\Controllers\MainStageController;
use App\Http\Controllers\NotifikasiController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\PreferencesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentHistoryController;
use App\Http\Controllers\PaymentConfirmationController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\PollingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware('auth')->group(function() {
    Route::get('/' , [HomeController::class , 'index'])->name('index');

    Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function () {
        Route::group(['prefix' => 'preferences' , 'as' => 'preferences.'], function () {
            Route::get('/' , [PreferencesController::class , 'index'])->name('index');
            Route::get('/event' , [PreferencesController::class , 'event'])->name('event');
            Route::post('/event/update/{preferences}' , [PreferencesController::class , 'eventUpdate'])->name('event-update');
            Route::get('/zoom' , [PreferencesController::class , 'zoom'])->name('zoom');
            Route::post('/zoom/update/{preferences}' , [PreferencesController::class , 'zoomUpdate'])->name('zoom-update');

            Route::get('/landing-page' , [PreferencesController::class , 'landing'])->name('landing');
            Route::post('/landing/update/{preferences}' , [PreferencesController::class , 'landingUpdate'])->name('landing-update');

            Route::get('/login' , [PreferencesController::class , 'login'])->name('login');
            Route::post('/login/update/{preferences}' , [PreferencesController::class , 'loginUpdate'])->name('login-update');

            Route::get('/payment' , [PreferencesController::class , 'payment'])->name('payment');
            Route::post('/payment/update/{preferences}' , [PreferencesController::class , 'paymentUpdate'])->name('payment-update');

            Route::get('/web' , [PreferencesController::class , 'web'])->name('web');
            Route::post('/web/update/{preferences}' , [PreferencesController::class , 'webUpdate'])->name('web-update');

            Route::post('/speaker/create' , [PreferencesController::class , 'speakerInsert'])->name('speaker.create');
            Route::get('/speaker/delete/{speaker}' , [PreferencesController::class , 'speakerDelete'])->name('speaker.delete');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');
            
        });

        Route::group(['prefix' => 'participant' , 'as' => 'participant.'], function (){
            Route::get('/web-regisration', [ParticipantController::class , 'web'])->name('web-regis');
            Route::get('/invitation', [ParticipantController::class , 'invite'])->name('invite');
            Route::get('/create' ,[ParticipantController::class , 'create'])->name('create');
            Route::post('/store' ,[ParticipantController::class , 'store'])->name('store');
            Route::get('/detail/{participant}', [ParticipantController::class , 'show'])->name('show');
            Route::get('/{participant}' ,[ParticipantController::class , 'destroy'])->name('delete');
            Route::get('/update/{participant}' ,[ParticipantController::class , 'edit'])->name('edit');
            Route::post('/edit/{participant}' ,[ParticipantController::class , 'update'])->name('update');
            
        });
        
        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'notifications' , 'as' => 'notif.'], function () {
            Route::get('/', [NotifikasiController::class , 'index'])->name('index');
            Route::get('/create' ,[NotifikasiController::class , 'create'])->name('create');
            Route::post('/store' ,[NotifikasiController::class , 'store'])->name('store');
            Route::get('/{notif}' ,[NotifikasiController::class , 'delete'])->name('delete');
            Route::get('/update/{notif}' ,[NotifikasiController::class , 'edit'])->name('edit');
            Route::post('/edit/{notif}' ,[NotifikasiController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');

        });

        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
            Route::get('/schedule/{ticket}' ,[TicketController::class , 'schedule'])->name('schedule');
            Route::get('/schedule-delete/{ticket}' ,[TicketController::class , 'scheduleDelete'])->name('schedule.delete');
        });

        Route::group(['prefix' => 'schedule' , 'as' => 'schedule.'], function () {
            /* Main Stage */
            Route::group(['prefix' => 'main-stage' , 'as' => 'main_stage.'], function () {
                Route::get('/', [MainStageController::class , 'index'])->name('index');
                Route::get('/create', [MainStageController::class , 'create'])->name('create');
                Route::post('/store', [MainStageController::class , 'store'])->name('store');
                Route::get('/{main_stage}/edit', [MainStageController::class , 'edit'])->name('edit');
                Route::post('/{main_stage}/update', [MainStageController::class , 'update'])->name('update');
                Route::get('/{main_stage}', [MainStageController::class , 'delete'])->name('delete');
                Route::get('/{main_stage}/attachment', [MainStageController::class , 'attachment'])->name('attachment');
                Route::get('/{main_stage}/attachment/create', [MainStageController::class , 'attachmentCreate'])->name('attachment.create');

app/Models/Polling.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Polling extends Model
{
    use HasFactory;

    protected $table = 'pollings';

    protected $dates = ['deleted_at'];

    protected $guarded = [];
}

app/Http/Controllers/PollingController.php
<?php

namespace App\Http\Controllers;

use Session;
use Carbon\Carbon;
use App\Models\Ticket;
use App\Models\Polling;
use App\Models\PollingDetail;
use Illuminate\Http\Request;
use Yajra\DataTables\Facades\DataTables;

class PollingController extends Controller
{
    public function index()
    {
        if(request()->ajax()){
            $data = Polling::latest()->get();
            return DataTables::of($data)->make(true);
        }
        return view('pages.pollings.index');
    }

    public function create()
    {
        $data       = null;
        $pollings   = null;
        return view('pages.pollings.action',compact('data', 'pollings'));
    }

    public function store(Request $request)
    {
        $polling = Polling::create([
            'name'      => $request->name,
            'status'    => 'active'
        ]);

        $number = count($request->question);
        for ($i=0; $i < $number; $i++) { 
            PollingDetail::create([
                'polling_id'    => $polling->id,
                'question'      => $request->question[$i],
                'options'       => $request->option[$i]
            ]);
        }

        Session::flash('success');
        return redirect()->route('admin.polling.index');
    }

    public function delete(Polling $polling)
    {
        $polling->delete();
        return response()->json();
    }

    public function edit(Polling $polling)
    {
        $data       = $polling;
        $pollings   = PollingDetail::where('polling_id', $polling->id)->get();
        return view('pages.pollings.action',compact('data', 'pollings'));
    }

    public function update(Request $request, Polling $polling)
    {

        $polling->update([
            'name'      => $request->name
        ]);

        PollingDetail::where('polling_id', $polling->id)->delete();

        $number = count($request->question);
        for ($i=0; $i < $number; $i++) { 
            PollingDetail::create([
                'polling_id'    => $polling->id,
                'question'      => $request->question[$i],
                'options'       => $request->option[$i]
            ]);
        }

        Session::flash('success');
        return redirect()->route('admin.polling.index');
    }

}

resources/views/pages/pollings/action.blade.php
@extends('layouts.app')
@section('content')

<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-pickadate.css">
<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

<div class="content-header row">
	<div class="content-header-left col-md-9 col-12 mb-2">
		<div class="row breadcrumbs-top">
			<div class="col-12">
				<div class="breadcrumb-wrapper">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a>
						</li>
						<li class="breadcrumb-item"><a href="{{ route('admin.schedule.main_stage.index') }}">Polling</a>
						</li>
						<li class="breadcrumb-item active">
							@if ($data !== null)
							Update Polling
							@else
							Create Polling
							@endif
						</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="content-body">
	<!-- Validation -->
	<section class="bs-validation">
		@if ($data !== null)
		<form action="{{ route('admin.polling.update', $data->id) }}" method="POST" enctype="multipart/form-data">        
		@else
		<form action="{{ route('admin.polling.store') }}" id="jquery-val-form" method="POST" enctype="multipart/form-data">
		@endif
		@csrf
		<div class="row">
			<!-- Bootstrap Validation -->
			<div class="col-md-12 col-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">Polling</h4>
					</div>
					<div class="card-body">
						<div class="form-group">
							<label class="form-label" for="basic-addon-name">Name</label>

							<input type="text" id="name" name="name" class="form-control" aria-label="Name" value="{{ $data ? $data->name : '' }}" aria-describedby="basic-addon-name" required />
							@error('name')
							<span class="text-danger">{{ $message }}</span>
							@enderror
						</div>
					</div>
				</div>
			</div>

			<div class="col-md-6 col-12">
				<div class="card">
					<div class="card-body">
						<div class="form-group">
							<label class="form-label" for="basic-addon-name">Question</label>

							<input type="text" id="question" name="question" class="form-control" aria-label="Name" value="{{ old('question') }}" aria-describedby="basic-addon-name" />
							@error('question')
							<span class="text-danger">{{ $message }}</span>
							@enderror
						</div>
						<div class="row">
							<div class="col-md-10">
								<div class="form-group">
									<label class="form-label" for="basic-addon-name">Option (At least 2 options)</label>

									<input type="text" id="option" name="option" class="form-control " aria-label="Name" value=" " aria-describedby="basic-addon-name" />
								</div>
							</div>
							<div class="col-md-2">
								<label class="form-label" for="basic-addon-name"></label>
								<div id="button-option">
									<button class="btn btn-info add-edit" type="button" id="add-option"><span class="fa fa-plus"></span></button>
								</div>
							</div>
						</div>
						<div class="form-group">
							<label class="form-label" for="basic-addon-name">Option List</label>

							<div class="table-responsive">
								<table class="table">
									<thead>
										<tr>
											<th>Option</th>
											<th>Action</th>
										</tr>
									</thead>
									<tbody id="tbody">
										
									</tbody>
								</table>
							</div>
						</div>
						<div class="row mt-2">
							<div class="col-md-6">
								<button type="button" class="btn btn-danger" id="add-list">Add List</button>
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="col-md-6 col-12">
				<h4 class="card-title text-center">Polling Question List</h4>
				<div id="list-question">
					@if($pollings)
					@foreach($pollings as $item)
					<div class="card" id="card-{{ $item->id }}">
						<div class="card-body">
							<div class="row">
								<div class="col-md-10">
									{{ $item->question }}
								</div>
								<div class="col-md-2">
									<button type="button" data-id="{{ $item->id }}" class="btn btn-danger delete-question"><i class="fa fa-trash"></i></button>
								</div>
							</div>
						</div>
					</div>
					@endforeach
					@endif
				</div>
			</div>
		</div>

		<div id="input-option">
			@php $no = 1 @endphp
			@if($pollings)
			@foreach($pollings as $item)
			@php $no += $item->id @endphp
			<input type="hidden" name="question[]" id="question-{{ $item->id }}" value="{{ $item->question }}">
				<input type="hidden" name="option[]" id="option-{{ $item->id }}"  value="{{ $item->options }}">
			@endforeach
			@endif
		</div>

		<div class="row mb-4">
			<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Save Changes</button>
			</div>
		</div>
	</form>
</section>
</div>
<input type="hidden" id="number" value="{{ $no }}" >
@endsection

@section('script')
<script type="text/javascript">
	$(document).on('click', '#add-option', function () {
		var option 		= $('#option').val();
		var question 	= $('#question').val();
		var name 		= $('#name').val();
		var number 		= $('#number').val();
		if (option 		=== ' ') {
			$('#option').addClass('is-invalid');
		} else {
			$('#option').removeClass('is-invalid');
		}
		if (question == '') {
			$('#question').addClass('is-invalid');
		} else {
			$('#question').removeClass('is-invalid');
		}
		if (name == '') {
			$('#name').addClass('is-invalid');
		} else {
			$('#name').removeClass('is-invalid');
		}
		if (option !== ' ' && question !== '' && name !== '') {
		$('#number').val(parseInt(number) + parseInt(1));
		$('#tbody').append(`
			<tr id="tr-${number}">
				<td id="td-${number}" class="td-option">${option}</td>
				<td><button class="btn btn-info edit" data-value="${option}" data-id="${number}" type="button"><span class="fa fa-edit"></span></button> <button class="btn btn-danger delete" data-id="${number}" type="button"><span class="fa fa-trash"></span></button></td>
			</tr>
			`);
		$('#option').val(' ')
		}
	});
	$(document).on('click', '.edit', function () {
		var id = $(this).attr('data-id');
		var value = $('#td-'+id).html();
		$('#option').val(value);

		$('#button-option').html(`<button class="btn btn-success add-edit" data-id="${id}" type="button" id="edit-option"><span class="fa fa-check"></span></button>`);
	});

	$(document).on('click', '.delete', function () {
		var id = $(this).attr('data-id');
		$('#tr-'+id).remove();
	});
	$(document).on('click', '.delete-question', function () {
		var id = $(this).attr('data-id');

		$('#card-'+id).remove();
		$('#question-'+id).remove();
		$('#option-'+id).remove();
	});

	$(document).on('click', '#edit-option', function () {
		var option = $('#option').val();
		var id = $(this).attr('data-id');
		if (option === ' ') {
			$('#option').addClass('is-invalid');
		} else {
			$('#option').removeClass('is-invalid');
		}
		if (option !== ' ') {
		$('#td-'+id).html(option);
		$('#option').val(' ')
		$('#button-option').html(`<button class="btn btn-info add-edit" type="button" id="add-option"><span class="fa fa-plus"></span></button>`);
		}
	});

	$(document).on('click', '#add-list', function () {
		var option 		= $('#option').val();
		var question 	= $('#question').val();
		var name 		= $('#name').val();
		var td 			= $(".td-option").length;
		var result 		= '';
		for (var i = 0; i < td; i++) {
			result += document.getElementsByClassName('td-option')[i].innerHTML + '|';
		}

		if (question == '') {
			$('#question').addClass('is-invalid');
		} else {
			$('#question').removeClass('is-invalid');
		}
		if (name == '') {
			$('#name').addClass('is-invalid');
		} else {
			$('#name').removeClass('is-invalid');
		}
		if (question !== '' && name !== '' && td >= 2) {
			var number 		= $('#number').val();
			$('#input-option').append(`
				<input type="hidden" name="question[]" id="question-${number}" value="${question}">
				<input type="hidden" name="option[]" id="option-${number}"  value="${result}">
				`);
			$('#option').val('');
			$('#question').val('');
			$('#tbody').html('');
			$('#list-question').append(`
								<div class="card" id="card-${number}">
									<div class="card-body">
										<div class="row">
											<div class="col-md-10">
												${question}
											</div>
											<div class="col-md-2">
												<button type="button" data-id="${number}" class="btn btn-danger delete-question"><i class="fa fa-trash"></i></button>
											</div>
										</div>
									</div>
								</div>
				`);
		}
	})
</script>
@endsection

resources/views/pages/pollings/index.blade.php
@extends('layouts.app')
@section('content')

<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Polling</h2>
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a>
                            </li>
                            <li class="breadcrumb-item"><a href="#">Polling</a>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- Basic table -->
        <section id="ajax-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h4 class="card-title">Polling</h4>
                            <a href="{{ route('admin.polling.create') }}" class="btn btn-primary">Add Data</a>
                        </div>
                        <div class="card-datatable">
                            <table class="table" id="data-notif">
                                <thead>
                                    <tr>
                                        <th>No</th>
                                        <th>Name</th>
                                        <th>Status</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Basic table -->


    </div>
</div>

@endsection

@section('script')

<!-- BEGIN: Page Vendor JS-->
<script src="/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/responsive.bootstrap4.js" defer></script>

<script src="/app-assets/js/scripts/tables/table-datatables-advanced.js" defer></script>
<script src="/app-assets/js/scripts/components/components-dropdowns.js"></script>
<!-- END: Page Vendor JS-->
<!-- BEGIN: Page JS-->


<script>
    $(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var table = $('#data-notif').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('admin.polling.index') }}",
            columns: [
            {
                data: null, "sortable": false,
                render: function (data, type, row, meta) { return meta.row + meta.settings._iDisplayStart + 1; },
            },
            {
                data: 'name',
                name: 'name',
            },
            {
                data: 'status',
                name: 'status',
            },
            {
                data: 'id',
                render: (id) => /* html */`
                <div class="btn-group">
                <button class="btn btn-flat-dark dropdown-toggle" type="button" id="dropdownMenuButton100" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <img src="/app-assets/images/align-justify.svg">
                </button>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="/admin/polling/update/${id}">Update</a>
                <a class="dropdown-item" href="javascript:void(0);" onclick="return hapus(${id})">Hapus</a>
                </div>
                </div>
                `
            },
            ],
            columnDefs: [
            {
                className: 'control',
                orderable: false,
                targets: 0
            }
            ],
            dom:
            '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
            orderCellsTop: true,
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function (row) {
                            var data = row.data();
                            return 'Details of ' + data['full_name'];
                        }
                    }),
                    type: 'column',
                    renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                        tableClass: 'table'
                    })
                }
            },
            language: {
                paginate: {
                    // remove previous & next text from pagination
                    previous: '&nbsp;',
                    next: '&nbsp;'
                }
            },
            drawCallback: () => {
                $('.delete').click(function () {
                    const id = $(this).data(id)
                })
            }
        });
    });

    function hapus(id){
        var table = $('#data-notif').DataTable();
        clearToastObj = toastr['error'](
            'Are You Delete?<br /><br /><button type="button" class="btn btn-danger btn-sm delete">Yes</button>',
            'Deleted',
            {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                tapToDismiss: false,
            }
            );

        if (clearToastObj.find('.delete').length) {
            clearToastObj.delegate('.delete', 'click', function () {
                toastr.clear(clearToastObj, { force: true });
                clearToastObj = undefined;
                $.ajax({
                    method: "GET",
                    url: "/admin/polling" + '/' + id,
                    success: function (data) {
                        toastr['success']('👋 Yes Data Deleted !!.', 'Progress Bar', {
                            closeButton: true,
                            tapToDismiss: false,
                            progressBar: true,
                        });
                        table.ajax.reload();
                    },
                    error: function (data) {
                        toastr['success']('👋 Chocolate oat cake jelly oat cake candy jelly beans pastry.', 'Progress Bar', {
                            closeButton: true,
                            tapToDismiss: false,
                            progressBar: true,
                            rtl: isRtl
                        });
                    }
                });
            });
        }
    }
</script>
<script>
    $(function (){
        $('.hapus').on('click', function () {
            var id = $(this).attr('data-id');
            console.log(id);
        });
    });
</script>
@if(Session::get('success'))
<script type="text/javascript">
    $(document).ready(function(){

         // Success Type
         toastr['success']('Successfully Update or Delete Data.', 'Successfully', {
            closeButton: true,
            tapToDismiss: false,
            progressBar: true,
        });

     });
 </script>
 @endif
 @endsection