routes/web.php
<?php

use App\Models\Participant;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoothController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\ClassroomController;
use App\Http\Controllers\MainStageController;
use App\Http\Controllers\NotifikasiController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\PreferencesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentHistoryController;
use App\Http\Controllers\PaymentConfirmationController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\PollingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware('auth')->group(function() {
    Route::get('/' , [HomeController::class , 'index'])->name('index');

    Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function () {
        Route::group(['prefix' => 'preferences' , 'as' => 'preferences.'], function () {
            Route::get('/' , [PreferencesController::class , 'index'])->name('index');
            Route::get('/event' , [PreferencesController::class , 'event'])->name('event');
            Route::post('/event/update/{preferences}' , [PreferencesController::class , 'eventUpdate'])->name('event-update');
            Route::get('/zoom' , [PreferencesController::class , 'zoom'])->name('zoom');
            Route::post('/zoom/update/{preferences}' , [PreferencesController::class , 'zoomUpdate'])->name('zoom-update');

            Route::get('/landing-page' , [PreferencesController::class , 'landing'])->name('landing');
            Route::post('/landing/update/{preferences}' , [PreferencesController::class , 'landingUpdate'])->name('landing-update');

            Route::get('/login' , [PreferencesController::class , 'login'])->name('login');
            Route::post('/login/update/{preferences}' , [PreferencesController::class , 'loginUpdate'])->name('login-update');

            Route::get('/payment' , [PreferencesController::class , 'payment'])->name('payment');
            Route::post('/payment/update/{preferences}' , [PreferencesController::class , 'paymentUpdate'])->name('payment-update');

            Route::get('/web' , [PreferencesController::class , 'web'])->name('web');
            Route::post('/web/update/{preferences}' , [PreferencesController::class , 'webUpdate'])->name('web-update');

            Route::post('/speaker/create' , [PreferencesController::class , 'speakerInsert'])->name('speaker.create');
            Route::get('/speaker/delete/{speaker}' , [PreferencesController::class , 'speakerDelete'])->name('speaker.delete');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');
            
        });

        Route::group(['prefix' => 'participant' , 'as' => 'participant.'], function (){
            Route::get('/web-regisration', [ParticipantController::class , 'web'])->name('web-regis');
            Route::get('/invitation', [ParticipantController::class , 'invite'])->name('invite');
            Route::get('/create' ,[ParticipantController::class , 'create'])->name('create');
            Route::post('/store' ,[ParticipantController::class , 'store'])->name('store');
            Route::get('/detail/{participant}', [ParticipantController::class , 'show'])->name('show');
            Route::get('/{participant}' ,[ParticipantController::class , 'destroy'])->name('delete');
            Route::get('/update/{participant}' ,[ParticipantController::class , 'edit'])->name('edit');
            Route::post('/edit/{participant}' ,[ParticipantController::class , 'update'])->name('update');
            
        });
        
        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'notifications' , 'as' => 'notif.'], function () {
            Route::get('/', [NotifikasiController::class , 'index'])->name('index');
            Route::get('/create' ,[NotifikasiController::class , 'create'])->name('create');
            Route::post('/store' ,[NotifikasiController::class , 'store'])->name('store');
            Route::get('/{notif}' ,[NotifikasiController::class , 'delete'])->name('delete');
            Route::get('/update/{notif}' ,[NotifikasiController::class , 'edit'])->name('edit');
            Route::post('/edit/{notif}' ,[NotifikasiController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');

        });

        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
            Route::get('/schedule/{ticket}' ,[TicketController::class , 'schedule'])->name('schedule');
            Route::get('/schedule-delete/{ticket}' ,[TicketController::class , 'scheduleDelete'])->name('schedule.delete');
        });

        Route::group(['prefix' => 'schedule' , 'as' => 'schedule.'], function () {
            /* Main Stage */
            Route::group(['prefix' => 'main-stage' , 'as' => 'main_stage.'], function () {
                Route::get('/', [MainStageController::class , 'index'])->name('index');
                Route::get('/create', [MainStageController::class , 'create'])->name('create');
                Route::post('/store', [MainStageController::class , 'store'])->name('store');
                Route::get('/{main_stage}/edit', [MainStageController::class , 'edit'])->name('edit');
                Route::post('/{main_stage}/update', [MainStageController::class , 'update'])->name('update');
                Route::get('/{main_stage}', [MainStageController::class , 'delete'])->name('delete');
                Route::get('/{main_stage}/attachment', [MainStageController::class , 'attachment'])->name('attachment');
                Route::get('/{main_stage}/attachment/create', [MainStageController::class , 'attachmentCreate'])->name('attachment.create');

app/Models/Payment.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Payment extends Model
{
    use HasFactory;

    protected $table = 'payments';

    protected $dates = ['deleted_at'];

    protected $guarded = [];

    public function participant()
    {
        return $this->belongsTo(Participant::class);
    }
}

resources/views/pages/payments/action.blade.php
@extends('layouts.app')
@section('content')

<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-flat-pickr.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/plugins/forms/pickers/form-pickadate.css">

<div class="content-header row">
	<div class="content-header-left col-md-9 col-12 mb-2">
		<div class="row breadcrumbs-top">
			<div class="col-12">
				<div class="breadcrumb-wrapper">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="#">Home</a>
						</li>
						<li class="breadcrumb-item"><a href="#">Ticket</a>
						</li>
						<li class="breadcrumb-item active">
							@if ($data !== null)
							Update Ticket
							@else
							Create Ticket
							@endif
						</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="content-body">
	<!-- Validation -->
	<section class="bs-validation">
		@if ($data !== null)
		<form action="{{ route('admin.ticket.update', $data->id) }}" method="POST">        
		@else
		<form action="{{ route('admin.ticket.store') }}" id="jquery-val-form" method="POST">
		@endif
		@csrf
		<div class="row">
			<!-- Bootstrap Validation -->
			<div class="col-md-12 col-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">Ticket</h4>
					</div>
					<div class="card-body">
						<div class="form-group">
							<label class="form-label" for="basic-addon-name">Name</label>

							<input type="text" id="basic-addon-name" name="name" class="form-control" aria-label="Name" value="{{ $data ? $data->name : '' }}" aria-describedby="basic-addon-name" required />
						</div>
						<div class="form-group">
							<label class="form-label" for="basic-addon-name">Description</label>

							<textarea name="description" id="message" class="form-control @error('description') border-danger @enderror" cols="30" rows="10">{{ $data ? $data->description : '' }}</textarea>
							@error('description')
							<span class="text-danger">{{ $message }}</span>
							@enderror
						</div>
						<div class="form-group">
							<label for="select-country1">Type </label>
							<select class="form-control" id="select-country1" name="type" required>
								@if($data)
								@if($data->type == 'paid')
								<option value="paid">Paid</option>
								<option value="free">Free</option>
								@else
								<option value="free">Free</option>
								<option value="paid">Paid</option>
								@endif
								@else
								<option value="paid">Paid</option>
								<option value="free">Free</option>
								@endif
							</select>
						</div>
						<div id="type-paid">
							@if($data)
							@if($data->type == 'paid')
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Price</label>

								<input type="number" id="basic-addon-name" name="price" class="form-control" aria-label="Name" value="{{ $data ? $data->price : '' }}" aria-describedby="basic-addon-name" required />
							</div>
							<div class="form-group">
								<label class="d-block">Ticket Only ?</label>
								<div class="custom-control custom-radio my-50">
									<input type="radio" id="validationRadio3" name="validationRadioBootstrap" class="custom-control-input" value="1" {{ $data ? $data->ticket_only == 1 ? 'checked' : '' : '' }} />
									<label class="custom-control-label" for="validationRadio3">Yes</label>
								</div>
								<div class="custom-control custom-radio">
									<input type="radio" id="validationRadio4" name="validationRadioBootstrap" class="custom-control-input" value="0" {{ $data ? $data->ticket_only == 0 ? 'checked' : '' : '' }}/>
									<label class="custom-control-label" for="validationRadio4">No</label>
								</div>
							</div>
							@else
							@endif
							@else
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Price</label>

								<input type="number" id="basic-addon-name" name="price" class="form-control" aria-label="Name" value="{{ $data ? $data->price : '' }}" aria-describedby="basic-addon-name" required />
							</div>
							<div class="form-group">
								<label class="d-block">Ticket Only ?</label>
								<div class="custom-control custom-radio my-50">
									<input type="radio" id="validationRadio3" name="validationRadioBootstrap" class="custom-control-input" value="1" {{ $data ? $data->ticket_only == 1 ? 'checked' : '' : 'checked' }} />
									<label class="custom-control-label" for="validationRadio3">Yes</label>
								</div>
								<div class="custom-control custom-radio">
									<input type="radio" id="validationRadio4" name="validationRadioBootstrap" class="custom-control-input" value="0" {{ $data ? $data->ticket_only == 0 ? 'checked' : '' : '' }}/>
									<label class="custom-control-label" for="validationRadio4">No</label>
								</div>
							</div>
							@endif
							
						</div>
					</div>
				</div>
				<div id="ticket">
					@if($data)
					@if($data->ticket_only == '0')
					<div class="row">
						<div class="col-md-6">
							<div class="card">
								<div class="card-body">
									<div class="form-group">
										<label class="form-label" for="basic-addon-name">Classroom Schedule</label>

										<select class="form-control" id="classroom_schedule" name="classroom_schedule" required>
											<option disabled="" selected="">Please Select a Classroom Schedule</option>
											@foreach($classroom as $item)
											<option value="{{ $item->id }}" data-title="{{ $item->title }}">{{ $item->title }}</option>
											@endforeach
										</select>
									</div>
									<div class="form-group">
										<label class="form-label" for="basic-addon-name">Price</label>

										<input type="number" id="price_schedule" name="price_schedule" class="form-control" aria-label="Name" aria-describedby="basic-addon-name" required />
									</div>
									 <button class="btn btn-primary" type="button" id="add-schedule">Add</button>

								</div>
							</div>
						</div>
						<div class="col-md-6" id="schedule">
							<h4>Ticket Schedule List</h4>
							<br>
							@foreach($ticketList as $item)
							<div class="card">
								<div class="card-body">
									<div class="row">
										<div class="col-md-10">
											{{ $item->schedule->title }} (Rp. {{ $item->price }})
										</div>
										<input type="hidden" value="{{ $item->schedule_id }}" name="schedule_id[]">
										<input type="hidden" value="{{ $item->price }}" name="schedule_price[]">
										<div class="col-md-2">
											<!-- <a ><i data-feather="edit" class="font-medium-3"></i></a> -->
											<a href="{{ route('admin.ticket.schedule.delete', $item->id) }}"><i data-feather="trash-2" class="font-medium-3"></i></a>
										</div>
									</div>
								</div>
							</div>
							@endforeach
						</div>
					</div>
					@endif
					@endif
				</div>
			</div>
		</div>

		<div class="row mb-4">
			<div class="col-md-6">
				<button type="submit" class="btn btn-primary">Save Changes</button>
			</div>
		</div>
	</form>
</section>
</div>
<input type="hidden" id="schedule_classroom">

@endsection

@section('script')
<script type="text/javascript">
	$(document).on('click', '#validationRadio3', function () {
		$('#ticket').html(``);
	});
	$(document).on('click', '#validationRadio4', function () {
		$('#ticket').html(`<div class="row">
						<div class="col-md-6">
							<div class="card">
								<div class="card-body">
									<div class="form-group">
										<label class="form-label" for="basic-addon-name">Classroom Schedule</label>

										<select class="form-control" id="classroom_schedule" name="classroom_schedule" required>
											<option disabled="" selected="">Please Select a Classroom Schedule</option>
											@foreach($classroom as $item)
											<option value="{{ $item->id }}" data-title="{{ $item->title }}">{{ $item->title }}</option>
											@endforeach
										</select>
									</div>
									<div class="form-group">
										<label class="form-label" for="basic-addon-name">Price</label>

										<input type="number" id="price_schedule" name="price_schedule" class="form-control" aria-label="Name" aria-describedby="basic-addon-name" required />
									</div>
									 <button class="btn btn-primary" type="button" id="add-schedule">Add</button>

								</div>
							</div>
						</div>
						<div class="col-md-6" id="schedule">
							<h4>Ticket Schedule List</h4>
							<br>
						</div>
					</div>`);
	});
	$('#select-country1').on('change', function () {
		var type = $('#select-country1').val();
		if (type == 'paid') {
			$('#type-paid').html(`
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Price</label>

								<input type="number" id="basic-addon-name" name="price" class="form-control" aria-label="Name" value="{{ $data ? $data->price : '' }}" aria-describedby="basic-addon-name" required />
							</div>
							<div class="form-group">
								<label class="d-block">Ticket Only ?</label>
								<div class="custom-control custom-radio my-50">
									<input type="radio" id="validationRadio3" name="validationRadioBootstrap" class="custom-control-input" value="1" {{ $data ? $data->ticket_only == 1 ? 'checked' : '' : '' }} />
									<label class="custom-control-label" for="validationRadio3">Yes</label>
								</div>
								<div class="custom-control custom-radio">
									<input type="radio" id="validationRadio4" name="validationRadioBootstrap" class="custom-control-input" value="0" {{ $data ? $data->ticket_only == 0 ? 'checked' : '' : '' }}/>
									<label class="custom-control-label" for="validationRadio4">No</label>
								</div>
							</div>`);
		} else {
			$('#type-paid').html(``);
		}
	});

	$(document).on('change', '#classroom_schedule', function () {
		var schedule 	= $('#classroom_schedule').val();
		$.ajax ({
			method: "GET",
			url: "/admin/ticket/schedule/"+schedule, 
			data: {"_token": "{{ csrf_token() }}",}
		}).done( function(data){
			$('#schedule_classroom').val(data.title)
		}).fail(function(jqXHR, textStatus, error){
		});
	});

	$(document).on('click', '#add-schedule', function () {
		var schedule 	= $('#schedule_classroom').val();
		var id 			= $('#classroom_schedule').val();
		var price 		= $('#price_schedule').val();
		if (schedule == null) {
			$('#classroom_schedule').addClass('is-invalid');
		} else {
			$('#classroom_schedule').removeClass('is-invalid');
		}
		if (price == '') {
			$('#price_schedule').addClass('is-invalid');
		} else {
			$('#price_schedule').removeClass('is-invalid');
		}
		if (schedule != null && price != '') {
			$('#schedule').append(`<div class="card">
									<div class="card-body">
										<div class="row">
											<div class="col-md-10">
												`+schedule+`(Rp.`+price+`)
											</div>
											<input type="hidden" value="`+id+`" name="schedule_id[]">
											<input type="hidden" value="`+price+`" name="schedule_price[]">
											<div class="col-md-2">
												<a ><i data-feather="edit" class="font-medium-3"></i></a>
												<a ><i data-feather="trash-2" class="font-medium-3"></i></a>
											</div>
										</div>
									</div>
								</div>`);
			$('#classroom_schedule').html(`
											<option disabled="" selected="">Please Select a Classroom Schedule</option>
											@foreach($classroom as $item)
											<option value="{{ $item->id }}" data-title="{{ $item->title }}">{{ $item->title }}</option>
											@endforeach`);
			$('#price_schedule').val();
		}
	});
</script>
@endsection

resources/views/pages/payments/confirmation.blade.php
@extends('layouts.app')
@section('content')

<div class="content-overlay"></div>
<div class="header-navbar-shadow"></div>
<div class="content-wrapper">
    <div class="content-header row">
        <div class="content-header-left col-md-9 col-12 mb-2">
            <div class="row breadcrumbs-top">
                <div class="col-12">
                    <h2 class="content-header-title float-left mb-0">Payment Confirmation</h2>
                    <div class="breadcrumb-wrapper">
                        <ol class="breadcrumb">
                            <li class="breadcrumb-item"><a href="/">Home</a>
                            </li>
                            <li class="breadcrumb-item active"><a href="#">Payment Confirmation</a>
                            </li>
                        </ol>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="content-body">
        <!-- Basic table -->
        <section id="ajax-datatable">
            <div class="row">
                <div class="col-12">
                    <div class="card">
                        <div class="card-header border-bottom">
                            <h4 class="card-title">Payment Confirmation</h4>
                        </div>
                        <div class="card-datatable">
                            <table class="table" id="data-notif">
                                <thead>
                                    <tr>
                                        <th></th>
                                        <th>Order Id</th>
                                        <th>Image Payment</th>
                                        <th>Acount Name</th>
                                        <th>Amount</th>
                                        <th>Transfer Date</th>
                                        <th>Status</th>
                                    </tr>
                                </thead>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--/ Basic table -->


    </div>
</div>

@endsection

@section('script')

<!-- BEGIN: Page Vendor JS-->
<script src="/app-assets/vendors/js/tables/datatable/jquery.dataTables.min.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/datatables.bootstrap4.min.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/dataTables.responsive.min.js" defer></script>
<script src="/app-assets/vendors/js/tables/datatable/responsive.bootstrap4.js" defer></script>

<script src="/app-assets/js/scripts/tables/table-datatables-advanced.js" defer></script>
<script src="/app-assets/js/scripts/components/components-dropdowns.js"></script>
<!-- END: Page Vendor JS-->
<!-- BEGIN: Page JS-->


<script>
    $(function(){
        $.ajaxSetup({
            headers: {
                'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
            }
        });

        var table = $('#data-notif').DataTable({
            processing: true,
            serverSide: true,
            ajax: "{{ route('admin.payments.confirmation.index') }}",
            columns: [
            {
                data: 'no',
               "render" : function (data, type, row) {
                    return ' ';
                } 
            },
            {
                data: 'order_id',
                name: 'order_id',
            },
            {
                data: 'image',
                "render" : function (data, type, row) {
                    if(row.image == '0')
                    {
                        return '-';
                    }else {
                        return `<img src="/img/payments/${row.image}" width="100">`;
                    }
                    
                } 
            },
            {
                data: 'account_name',
                name: 'account_name',
            },
            {
                data: 'amount',
                name: 'amount',
            },
            {
                data: 'created_at',
                name: 'created_at',
            },
            {
                data: 'status',
               "render" : function (data, type, row) {
                    if(row.status == 'waiting')
                    {
                        return `<div class="btn-group">
                        <span class="badge badge-warning dropdown-toggle" id="dropdownMenuButton100" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        WAITING
                        </span>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                        <a class="dropdown-item" href="/admin/payments/confirmation/approved/${row.id}">Appproved</a>
                        <a class="dropdown-item" href="/admin/payments/confirmation/rejected/${row.id}">Rejected</a>
                        </div>
                        </div>`;
                    }else if(row.status == 'approved'){                                
                        return '<span class="badge badge-success">APPROVED</span>';
                    } else {
                        return '<span class="badge badge-danger">REJECTTED</span>';
                    }
                    
                } 
            },
            ],
            columnDefs: [
            {
                className: 'control',
                orderable: false,
                targets: 0
            }
            ],
            dom:
            '<"d-flex justify-content-between align-items-center mx-0 row"<"col-sm-12 col-md-6"l><"col-sm-12 col-md-6"f>>t<"d-flex justify-content-between mx-0 row"<"col-sm-12 col-md-6"i><"col-sm-12 col-md-6"p>>',
            orderCellsTop: true,
            responsive: {
                details: {
                    display: $.fn.dataTable.Responsive.display.modal({
                        header: function (row) {
                            var data = row.data();
                            return 'Details of ' + data['full_name'];
                        }
                    }),
                    type: 'column',
                    renderer: $.fn.dataTable.Responsive.renderer.tableAll({
                        tableClass: 'table'
                    })
                }
            },
            language: {
                paginate: {
                    // remove previous & next text from pagination
                    previous: '&nbsp;',
                    next: '&nbsp;'
                }
            },
            drawCallback: () => {
                $('.delete').click(function () {
                    const id = $(this).data(id)
                })
            }
        });
    });

    function hapus(id){
        clearToastObj = toastr['error'](
            'Are You Delete?<br /><br /><button type="button" class="btn btn-danger btn-sm delete">Yes</button>',
            'Deleted',
            {
                closeButton: true,
                timeOut: 0,
                extendedTimeOut: 0,
                tapToDismiss: false,
            }
            );

        if (clearToastObj.find('.delete').length) {
            clearToastObj.delegate('.delete', 'click', function () {
                toastr.clear(clearToastObj, { force: true });
                clearToastObj = undefined;
                $.ajax({
                    method: "GET",
                    url: "/admin/ticket" + '/' + id,
                    success: function (data) {
                        toastr['success']('👋 Yes Data Deleted !!.', 'Progress Bar', {
                            closeButton: true,
                            tapToDismiss: false,
                            progressBar: true,
                        });
                        location.reload();
                    },
                    error: function (data) {
                        toastr['success']('👋 Chocolate oat cake jelly oat cake candy jelly beans pastry.', 'Progress Bar', {
                            closeButton: true,
                            tapToDismiss: false,
                            progressBar: true,
                            rtl: isRtl
                        });
                    }
                });
            });
        }
    }
</script>
<script>
    $(function (){
        $('.hapus').on('click', function () {
            var id = $(this).attr('data-id');
            console.log(id);
        });
    });
</script>
@if(Session::get('success'))
<script type="text/javascript">
    $(document).ready(function(){

         // Success Type
         toastr['success']('Successfully Update or Delete Data.', 'Successfully', {
            closeButton: true,
            tapToDismiss: false,
            progressBar: true,
        });

     });
 </script>
 @endif
 @endsection