routes/web.php
<?php

use App\Models\Participant;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\BoothController;
use App\Http\Controllers\BannerController;
use App\Http\Controllers\TicketController;
use App\Http\Controllers\ClassroomController;
use App\Http\Controllers\MainStageController;
use App\Http\Controllers\NotifikasiController;
use App\Http\Controllers\ParticipantController;
use App\Http\Controllers\PreferencesController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\PaymentHistoryController;
use App\Http\Controllers\PaymentConfirmationController;
use App\Http\Controllers\SponsorController;
use App\Http\Controllers\PollingController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::middleware('auth')->group(function() {
    Route::get('/' , [HomeController::class , 'index'])->name('index');

    Route::group(['prefix' => 'admin' , 'as' => 'admin.'], function () {
        Route::group(['prefix' => 'preferences' , 'as' => 'preferences.'], function () {
            Route::get('/' , [PreferencesController::class , 'index'])->name('index');
            Route::get('/event' , [PreferencesController::class , 'event'])->name('event');
            Route::post('/event/update/{preferences}' , [PreferencesController::class , 'eventUpdate'])->name('event-update');
            Route::get('/zoom' , [PreferencesController::class , 'zoom'])->name('zoom');
            Route::post('/zoom/update/{preferences}' , [PreferencesController::class , 'zoomUpdate'])->name('zoom-update');

            Route::get('/landing-page' , [PreferencesController::class , 'landing'])->name('landing');
            Route::post('/landing/update/{preferences}' , [PreferencesController::class , 'landingUpdate'])->name('landing-update');

            Route::get('/login' , [PreferencesController::class , 'login'])->name('login');
            Route::post('/login/update/{preferences}' , [PreferencesController::class , 'loginUpdate'])->name('login-update');

            Route::get('/payment' , [PreferencesController::class , 'payment'])->name('payment');
            Route::post('/payment/update/{preferences}' , [PreferencesController::class , 'paymentUpdate'])->name('payment-update');

            Route::get('/web' , [PreferencesController::class , 'web'])->name('web');
            Route::post('/web/update/{preferences}' , [PreferencesController::class , 'webUpdate'])->name('web-update');

            Route::post('/speaker/create' , [PreferencesController::class , 'speakerInsert'])->name('speaker.create');
            Route::get('/speaker/delete/{speaker}' , [PreferencesController::class , 'speakerDelete'])->name('speaker.delete');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');
            
        });

        Route::group(['prefix' => 'participant' , 'as' => 'participant.'], function (){
            Route::get('/web-regisration', [ParticipantController::class , 'web'])->name('web-regis');
            Route::get('/invitation', [ParticipantController::class , 'invite'])->name('invite');
            Route::get('/create' ,[ParticipantController::class , 'create'])->name('create');
            Route::post('/store' ,[ParticipantController::class , 'store'])->name('store');
            Route::get('/detail/{participant}', [ParticipantController::class , 'show'])->name('show');
            Route::get('/{participant}' ,[ParticipantController::class , 'destroy'])->name('delete');
            Route::get('/update/{participant}' ,[ParticipantController::class , 'edit'])->name('edit');
            Route::post('/edit/{participant}' ,[ParticipantController::class , 'update'])->name('update');
            
        });
        
        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'notifications' , 'as' => 'notif.'], function () {
            Route::get('/', [NotifikasiController::class , 'index'])->name('index');
            Route::get('/create' ,[NotifikasiController::class , 'create'])->name('create');
            Route::post('/store' ,[NotifikasiController::class , 'store'])->name('store');
            Route::get('/{notif}' ,[NotifikasiController::class , 'delete'])->name('delete');
            Route::get('/update/{notif}' ,[NotifikasiController::class , 'edit'])->name('edit');
            Route::post('/edit/{notif}' ,[NotifikasiController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'booth' , 'as' => 'booth.'], function (){
            Route::get('/', [BoothController::class , 'index'])->name('index');
            Route::get('/create' ,[BoothController::class , 'create'])->name('create');
            Route::post('/store' ,[BoothController::class , 'store'])->name('store');
            Route::get('/{booth}' ,[BoothController::class , 'destroy'])->name('delete');
            Route::get('/update/{booth}' ,[BoothController::class , 'edit'])->name('edit');
            Route::post('/edit/{booth}' ,[BoothController::class , 'update'])->name('update');
        });

        Route::group(['prefix' => 'banner' , 'as' => 'banner.'], function (){
            Route::get('/image', [BannerController::class , 'image'])->name('image');
            Route::get('/youtube', [BannerController::class , 'youtube'])->name('youtube');
            Route::get('/create' ,[BannerController::class , 'create'])->name('create');
            Route::post('/store' ,[BannerController::class , 'store'])->name('store');
            Route::get('/{banner}' ,[BannerController::class , 'destroy'])->name('delete');
            Route::get('/update/{banner}' ,[BannerController::class , 'edit'])->name('edit');
            Route::post('/edit/{banner}' ,[BannerController::class , 'update'])->name('update');

        });

        Route::group(['prefix' => 'ticket' , 'as' => 'ticket.'], function () {
            Route::get('/', [TicketController::class , 'index'])->name('index');
            Route::get('/create' ,[TicketController::class , 'create'])->name('create');
            Route::post('/store' ,[TicketController::class , 'store'])->name('store');
            Route::get('/{ticket}' ,[TicketController::class , 'delete'])->name('delete');
            Route::get('/update/{ticket}' ,[TicketController::class , 'edit'])->name('edit');
            Route::post('/edit/{ticket}' ,[TicketController::class , 'update'])->name('update');
            Route::get('/schedule/{ticket}' ,[TicketController::class , 'schedule'])->name('schedule');
            Route::get('/schedule-delete/{ticket}' ,[TicketController::class , 'scheduleDelete'])->name('schedule.delete');
        });

        Route::group(['prefix' => 'schedule' , 'as' => 'schedule.'], function () {
            /* Main Stage */
            Route::group(['prefix' => 'main-stage' , 'as' => 'main_stage.'], function () {
                Route::get('/', [MainStageController::class , 'index'])->name('index');
                Route::get('/create', [MainStageController::class , 'create'])->name('create');
                Route::post('/store', [MainStageController::class , 'store'])->name('store');
                Route::get('/{main_stage}/edit', [MainStageController::class , 'edit'])->name('edit');
                Route::post('/{main_stage}/update', [MainStageController::class , 'update'])->name('update');
                Route::get('/{main_stage}', [MainStageController::class , 'delete'])->name('delete');
                Route::get('/{main_stage}/attachment', [MainStageController::class , 'attachment'])->name('attachment');
                Route::get('/{main_stage}/attachment/create', [MainStageController::class , 'attachmentCreate'])->name('attachment.create');

app/Models/Preference.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Preference extends Model
{
    use HasFactory;
    protected $table = 'preferences';

    protected $dates = ['deleted_at'];

    protected $guarded = [];

    protected $casts = [
        'action' => 'array'
    ];
}

resources/views/pages/preferences/event.blade.php
@extends('layouts.app')
@section('content')

<div class="content-header row">
	<div class="content-header-left col-md-9 col-12 mb-2">
		<div class="row breadcrumbs-top">
			<div class="col-12">
				<div class="breadcrumb-wrapper">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="/">Home</a>
						</li>
						<li class="breadcrumb-item"><a href="{{ route('admin.preferences.index') }}">Preferences</a>
						</li>
						<li class="breadcrumb-item active">Event
						</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="content-body">
	<!-- Validation -->
	<section class="bs-validation">
		<form action="{{ route('admin.preferences.event-update', $event->id) }}" method="POST" enctype="multipart/form-data">
			@csrf
			<div class="row">
				<!-- Bootstrap Validation -->
				<div class="col-md-12 col-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Event</h4>
						</div>
						<div class="card-body">
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Event Name</label>

								<input type="text" id="basic-addon-name" name="event_name" class="form-control" placeholder="Event Name" aria-label="Name" value="{{ $event ? $event->action['event_name'] : '' }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Date Start</label>

								<input type="date" id="basic-addon-name" name="date_start" class="form-control" placeholder="Event Name" aria-label="Name" value="{{ $event ? $event->action['date_start'] : '' }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Date End</label>

								<input type="date" id="basic-addon-name" name="date_end" class="form-control" placeholder="Event Name" aria-label="Name" value="{{ $event ? $event->action['date_end'] : '' }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>
							<div class="form-group">
								<label for="select-country1">Timezone </label>
								<select class="form-control" id="select-country1" name="timezone" required>
									<option value="{{ $event ? $event->action['timezone'] : '' }}">{{ $event ? $event->action['timezone'] : 'Select Timezone' }}</option>
									<option value="Asia/Jakart">Asia/Jakarta</option>
									<option value="Asia/Makassar">Asia/Makassar</option>
									<option value="Asia/Jayapura">Asia/Jayapura</option>
								</select>
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please select your country</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row">
				<!-- Bootstrap Validation -->
				<div class="col-md-6 col-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Logo & Icon</h4>
						</div>
						<div class="card-body">
							<div class="form-group">
								<label for="customFile1">Logo</label>
								<div class="custom-file">
									<input type="file" class="custom-file-input" name="logo" onchange="loadFile(event)" id="customFile1" />
									<label class="custom-file-label" for="customFile1">Choose logo pic</label>
								</div>
								<small>* If you want to upload other file, please first delete the file.</small>
								<img
                                    id="foto_profile"
                                    class="m-2"
                                    style="width:20%;border: 1px solid #ddd;border-radius: 4px;padding: 5px;width: 150px;"
                                    src="/img/event/{{ $event->action['logo'] }}">
							</div>
							<div class="form-group">
								<label for="customFile1">Icon</label>
								<div class="custom-file">
									<input type="file" class="custom-file-input" name="icon" onchange="loadFile2(event)" id="customFile1" />
									<label class="custom-file-label" for="customFile1">Choose icon pic</label>
								</div>
								<small>* If you want to upload other file, please first delete the file.</small>
								<img
                                    id="foto_profile2"
                                    class="m-2"
                                    style="width:20%;border: 1px solid #ddd;border-radius: 4px;padding: 5px;width: 150px;"
                                    src="/img/event/{{ $event->action['icon'] }}">
							</div>
						</div>
					</div>
				</div>
				<div class="col-md-6 col-12">
					<div class="card">
						<div class="card-header">
							<h4 class="card-title">Color</h4>
						</div>
						<div class="card-body">

							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Primary Color</label>

								<input type="color" value="{{ $event ? $event->action['primary_color'] : '' }}" id="basic-addon-name" name="primary_color" class="form-control" placeholder="Primary Color" aria-label="Name" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your primary color.</div>
							</div>

							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Secondary Color</label>

								<input type="color" value="{{ $event ? $event->action['secondary_color'] : '' }}" id="basic-addon-name" name="secondary_color" class="form-control" placeholder="Secondary Color" aria-label="Name" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your secondary color.</div>
							</div>

							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Tertiary Color</label>

								<input type="color" value="{{ $event ? $event->action['tertiary_color'] : '' }}" id="basic-addon-name" name="tertiary_color" class="form-control" placeholder="Tertiary Color" aria-label="Name" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your primary color.</div>
							</div>
						</div>
					</div>
				</div>
			</div>

			<div class="row mb-4">
				<div class="col-md-6">
					<button type="submit" class="btn btn-primary">Save Changes</button>
				</div>
			</div>
		</form>
	</section>
</div>
@endsection
@section('script')
@if(Session::get('success'))
<script type="text/javascript">
	$(document).ready(function(){

		 // Success Type
		 toastr['success']('Successfully Update or Delete Data.', 'Successfully', {
		 	closeButton: true,
		 	tapToDismiss: false,
		 	progressBar: true,
		 });

	});
</script>
@endif
@endsection

resources/views/pages/preferences/index.blade.php
@extends('layouts.app')
@section('content')
<section id="dashboard-analytics">
	<div class="row match-height">

		<!-- Subscribers Chart Card starts -->
		<div class="col-lg-6 col-sm-6 col-12">
			<div class="card">
				<div class="row">
					<div class="col-lg-3">
						
						<div class="card-header flex-column align-items-start pb-0">
							<div class="avatar bg-light-primary p-50 m-0">
								<div class="avatar-content">
									<i data-feather="users" class="font-medium-5"></i>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						
						<div class="card-header flex-column align-items-start pb-0">
							<h2 class="font-weight-bolder mt-1">Event</h2>
							<p>General settings such as, event name, event date, menu etc.</p>
							<a href="{{ route('admin.preferences.event') }}" class="my-2">Change Setting <i data-feather="chevron-right" class="font-medium-5"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Subscribers Chart Card ends -->

		<!-- Subscribers Chart Card starts -->
		<div class="col-lg-6 col-sm-6 col-12">
			<div class="card">
				<div class="row">
					<div class="col-lg-3">
						
						<div class="card-header flex-column align-items-start pb-0">
							<div class="avatar bg-light-primary p-50 m-0">
								<div class="avatar-content">
									<i data-feather="users" class="font-medium-5"></i>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						
						<div class="card-header flex-column align-items-start pb-0">
							<h2 class="font-weight-bolder mt-1">Zoom</h2>
							<p>General settings such as, zoom api key and zoom api secret.</p>
							<a href="{{ route('admin.preferences.zoom') }}" class="my-2">Change Setting <i data-feather="chevron-right" class="font-medium-5"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Subscribers Chart Card ends -->

		<!-- Subscribers Chart Card starts -->
		<div class="col-lg-6 col-sm-6 col-12">
			<div class="card">
				<div class="row">
					<div class="col-lg-3">
						
						<div class="card-header flex-column align-items-start pb-0">
							<div class="avatar bg-light-primary p-50 m-0">
								<div class="avatar-content">
									<i data-feather="users" class="font-medium-5"></i>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						
						<div class="card-header flex-column align-items-start pb-0">
							<h2 class="font-weight-bolder mt-1">Landing Page</h2>
							<p>Landing Page settings, such as poster image, about, speakers etc.</p>
							<a href="{{ route('admin.preferences.landing') }}" class="my-2">Change Setting <i data-feather="chevron-right" class="font-medium-5"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Subscribers Chart Card ends -->

		<!-- Subscribers Chart Card starts -->
		<div class="col-lg-6 col-sm-6 col-12">
			<div class="card">
				<div class="row">
					<div class="col-lg-3">
						
						<div class="card-header flex-column align-items-start pb-0">
							<div class="avatar bg-light-primary p-50 m-0">
								<div class="avatar-content">
									<i data-feather="users" class="font-medium-5"></i>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						
						<div class="card-header flex-column align-items-start pb-0">
							<h2 class="font-weight-bolder mt-1">Login & Register</h2>
							<p>Login & Register Settings such as title, banner, caption etc.</p>
							<a href="{{ route('admin.preferences.login') }}" class="my-2">Change Setting <i data-feather="chevron-right" class="font-medium-5"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Subscribers Chart Card ends -->

		<!-- Subscribers Chart Card starts -->
		<div class="col-lg-6 col-sm-6 col-12">
			<div class="card">
				<div class="row">
					<div class="col-lg-3">
						
						<div class="card-header flex-column align-items-start pb-0">
							<div class="avatar bg-light-primary p-50 m-0">
								<div class="avatar-content">
									<i data-feather="users" class="font-medium-5"></i>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						
						<div class="card-header flex-column align-items-start pb-0">
							<h2 class="font-weight-bolder mt-1">Payment</h2>
							<p>Payment Settings, such as title, caption, contact, bank transfer etc.</p>
							<a href="{{ route('admin.preferences.payment') }}" class="my-2">Change Setting <i data-feather="chevron-right" class="font-medium-5"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Subscribers Chart Card ends -->

		<!-- Subscribers Chart Card starts -->
		<div class="col-lg-6 col-sm-6 col-12">
			<div class="card">
				<div class="row">
					<div class="col-lg-3">
						
						<div class="card-header flex-column align-items-start pb-0">
							<div class="avatar bg-light-primary p-50 m-0">
								<div class="avatar-content">
									<i data-feather="users" class="font-medium-5"></i>
								</div>
							</div>
						</div>
					</div>
					<div class="col-lg-9">
						
						<div class="card-header flex-column align-items-start pb-0">
							<h2 class="font-weight-bolder mt-1">Web</h2>
							<p>Web Settings, such as menu icon, status, design etc.</p>
							<a href="{{ route('admin.preferences.web') }}" class="my-2">Change Setting <i data-feather="chevron-right" class="font-medium-5"></i></a>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- Subscribers Chart Card ends -->

	</div>
</section>
@endsection

resources/views/pages/preferences/landing.blade.php
@extends('layouts.app')
@section('content')

<div class="content-header row">
	<div class="content-header-left col-md-9 col-12 mb-2">
		<div class="row breadcrumbs-top">
			<div class="col-12">
				<div class="breadcrumb-wrapper">
					<ol class="breadcrumb">
						<li class="breadcrumb-item"><a href="index.html">Home</a>
						</li>
						<li class="breadcrumb-item"><a href="{{ route('admin.preferences.index') }}">Preferences</a>
						</li>
						<li class="breadcrumb-item active">Landing Page
						</li>
					</ol>
				</div>
			</div>
		</div>
	</div>
</div>
<div class="content-body">
	<!-- Validation -->
	<section class="bs-validation">
		<form action="{{ route('admin.preferences.landing-update', $landing->id) }}" method="POST" enctype="multipart/form-data">
			@csrf
			<div class="row">
				<!-- Bootstrap Validation -->
				<div class="col-md-6 col-12">
					<div class="card">
						<div class="card-body">
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Landing Page Banner</label>

								<input type="file" id="basic-addon-name" name="image" class="form-control" placeholder="Event Name" aria-label="Name" value="{{ $landing ? $landing->action['image'] : '' }}" aria-describedby="basic-addon-name" onchange="loadFile(event)"/>
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
								<small>* If you want to upload other file, please first delete the file.</small>
								<img
                                    id="foto_profile"
                                    class="m-2"
                                    style="width:20%;border: 1px solid #ddd;border-radius: 4px;padding: 5px;width: 150px;"
                                    src="/img/landing/{{ $landing->action['image'] }}">
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-6 col-12">
					<div class="card">
						<div class="card-body">
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Landingpage About Title Text *</label>

								<input type="text" id="basic-addon-name" name="title" class="form-control" aria-label="Name" value="{{ $landing ? $landing->action['title'] : '' }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>

							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Landingpage About Description Text *</label>
								<textarea name="description" class="form-control" required="">{{ $landing ? $landing->action['description'] : '' }}
								</textarea>
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>

							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Landingpage Footer Text *</label>

								<input type="text" id="basic-addon-name" name="footer_text" class="form-control" aria-label="Name" value="{{ $landing ? $landing->action['footer_text'] : '' }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>
						</div>
					</div>
				</div>

				<div class="col-md-12 mx-auto d-block">
					<div class="row mb-4">
						<div class="col-md-6">
							<button type="submit" class="btn btn-primary">Save Changes</button>
						</div>
					</div>
				</div>
			</form>

			<div class="col-md-6 col-12">
				<div class="card">
					<div class="card-header">
						<h4 class="card-title">Add New Speaker</h4>
					</div>
					<div class="card-body">
						<form action="{{ route('admin.preferences.speaker.create') }}" method="POST" enctype="multipart/form-data">
							@csrf
							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Name</label>

								<input type="text" id="basic-addon-name" name="name" class="form-control" aria-label="Name" value="{{ old('name') }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>

							<div class="form-group">
								<label class="form-label" for="basic-addon-name">Title (optional)</label>

								<input type="text" id="basic-addon-name" name="title" class="form-control" aria-label="Name" value="{{ old('title') }}" aria-describedby="basic-addon-name" required />
								<div class="valid-feedback">Looks good!</div>
								<div class="invalid-feedback">Please enter your name.</div>
							</div>

							<div class="form-group">
								<label for="customFile1">Profile Photo (optional)</label>
								<div class="custom-file">
									<input type="file" class="custom-file-input" name="image" id="customFile1" required />
									<label class="custom-file-label" for="customFile1">Choose profile pic</label>
								</div>
								<small>* Max size 500KB Square dimentions</small>
							</div>
							<div class="form-group">
								<input type="submit" value="Add" class="btn btn-warning">
							</div>
						</form>
					</div>
				</div>
			</div>
			<div class="col-md-6 col-12">
				<h4 class="card-title">Speakers</h4>
				@foreach($speaker as $item)
				<div class="media-list ">
					<div class="media bg-white">
						<div class="media-left">
							<img src="/img/speaker/{{ $item->image }}" alt="avatar" height="64" width="64" class="cursor-pointer" />
						</div>
						<div class="media-body">
							<h4 class="media-heading mt-2">{{ $item->name }} {{ $item->title ? '('.$item->title.')' : '' }}</h4>
						</div>
						<div class="media-right">
							<a href="{{ route('admin.preferences.speaker.delete', $item->id) }}" ><i data-feather="trash-2" class="font-medium-3"></i></a>
						</div>
					</div>
				</div>
				@endforeach
			</div>
		</div>
	</section>
</div>
@endsection
@section('script')
@if(Session::get('success'))
<script type="text/javascript">
	$(document).ready(function(){

		 // Success Type
		 toastr['success']('Successfully Update or Delete Data.', 'Successfully', {
		 	closeButton: true,
		 	tapToDismiss: false,
		 	progressBar: true,
		 });

	});
</script>
@endif
@endsection